version: "3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: "project-1_db"
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: "project-1_web"
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/var/www
    working_dir: /var/www/
    tty: true
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - db